<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
        h1 { font-size: 20px; text-align: center; margin-bottom: 5px; }
        h2 { font-size: 14px; margin-top: 20px; border-bottom: 2px solid #333; padding-bottom: 3px; }
        .summary { display: flex; justify-content: space-between; margin: 15px 0; }
        .summary-box { width: 23%; border: 1px solid #ddd; padding: 10px; text-align: center; }
        .summary-box .label { font-size: 10px; color: #666; text-transform: uppercase; }
        .summary-box .value { font-size: 18px; font-weight: bold; margin-top: 5px; }
        .positive { color: #16a34a; }
        .negative { color: #dc2626; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        th { background: #f0f0f0; padding: 8px; text-align: left; border: 1px solid #ddd; font-size: 11px; }
        td { padding: 6px 8px; border: 1px solid #ddd; }
        .footer { text-align: center; color: #999; font-size: 10px; margin-top: 30px; }
    </style>
</head>
<body>
    <h1>FinTrack - Monthly Report</h1>
    <p style="text-align: center; color: #666;">{{ $month }} | {{ $user->name }}</p>

    <h2>Summary</h2>
    <div class="summary">
        <div class="summary-box">
            <div class="label">Income</div>
            <div class="value positive">{{ number_format($total_income, 2) }}</div>
        </div>
        <div class="summary-box">
            <div class="label">Expense</div>
            <div class="value negative">{{ number_format($total_expense, 2) }}</div>
        </div>
        <div class="summary-box">
            <div class="label">Net</div>
            <div class="value {{ $net >= 0 ? 'positive' : 'negative' }}">{{ number_format($net, 2) }}</div>
        </div>
        <div class="summary-box">
            <div class="label">Savings Rate</div>
            <div class="value">{{ $savings_rate }}%</div>
        </div>
    </div>

    @if(count($category_breakdown) > 0)
    <h2>Category Breakdown</h2>
    <table>
        <thead>
            <tr>
                <th>Category</th>
                <th>Total</th>
                <th>%</th>
            </tr>
        </thead>
        <tbody>
            @foreach($category_breakdown as $cat)
            <tr>
                <td>{{ $cat['name'] }}</td>
                <td>{{ number_format($cat['total'], 2) }}</td>
                <td>{{ $cat['percentage'] }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if(count($top_merchants) > 0)
    <h2>Top Merchants</h2>
    <table>
        <thead>
            <tr>
                <th>Merchant</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($top_merchants as $merchant)
            <tr>
                <td>{{ $merchant['name'] }}</td>
                <td>{{ number_format($merchant['total'], 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <h2>Month Comparison</h2>
    <table>
        <thead>
            <tr>
                <th>Metric</th>
                <th>Previous Month</th>
                <th>This Month</th>
                <th>Change</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Income</td>
                <td>{{ number_format($prev_income, 2) }}</td>
                <td>{{ number_format($total_income, 2) }}</td>
                <td class="{{ $income_change >= 0 ? 'positive' : 'negative' }}">{{ $income_change }}%</td>
            </tr>
            <tr>
                <td>Expense</td>
                <td>{{ number_format($prev_expense, 2) }}</td>
                <td>{{ number_format($total_expense, 2) }}</td>
                <td class="{{ $expense_change <= 0 ? 'positive' : 'negative' }}">{{ $expense_change }}%</td>
            </tr>
        </tbody>
    </table>

    <h2>Transactions ({{ $transaction_count }})</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Category</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Wallet</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $tx)
            <tr>
                <td>{{ $tx['date'] }}</td>
                <td>{{ $tx['type'] }}</td>
                <td>{{ $tx['category'] }}</td>
                <td>{{ $tx['description'] }}</td>
                <td>{{ $tx['amount'] }}</td>
                <td>{{ $tx['wallet'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">Generated by FinTrack on {{ now()->format('Y-m-d H:i') }}</div>
</body>
</html>
